require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'pkg/*'
    - 'bin/*'
    - 'team-maker-integrations.gemspec'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - spec/**/*
Style/Lambda:
  EnforcedStyle: literal